opensourceways/xihe-server

- controller/training.go
The duration may not change in 5 seconds. it should keep the consistency of duration.
> fix the training duration

- app/bigmodel.go
- app/bigmodel_dto.go
- controller/bigmodel.go
- controller/bigmodel_request.go
- domain/bigmodel.go
- domain/bigmodel/models.go
- domain/repository/wukong.go
- infrastructure/bigmodels/obs.go
- infrastructure/bigmodels/wukong.go
- infrastructure/mongodb/doc.go
- infrastructure/mongodb/wukong_picture.go
- infrastructure/repositories/wukong_picture.go
1. fix addlikes bugs
2. add field "owner" to wukongPictureItem
3. add new interface
1. addPublicPicture
2. ListPublicPicture
3. GetPublicPictureGlobal
> add series interface of publics

- app/bigmodel.go
- app/bigmodel_dto.go
- app/finetune.go
- app/fork.go
- app/training.go
- controller/bigmodel.go
- controller/bigmodel_request.go
- domain/repository/wukong.go
- infrastructure/bigmodels/wukong.go
- infrastructure/mongodb/wukong_picture.go
- infrastructure/repositories/wukong_picture.go
- server/gin.go
1. new interface addDigg, cancelDigg, cancelPublic
2. add paginator for GetPublicGlobal
> new interface and paginator

- app/bigmodel.go
- infrastructure/bigmodels/check.go
- infrastructure/bigmodels/wukong.go
add image check based on HW Cloud Modration
> add img check

- infrastructure/bigmodels/wukong.go
replace "https://" to "" in cfg.Endpoint
> fix: fix wukong link generator

- app/bigmodel.go
- app/bigmodel_dto.go
- controller/bigmodel_request.go
- domain/repository/wukong.go
- infrastructure/repositories/wukong_picture.go
repositories.SaveLike can only store picture that belong to the user themselves, not other users.
so we fixed it make it compatible different picture sources
> fix: add like from public

- app/bigmodel.go
- app/bigmodel_dto.go
- controller/bigmodel_request.go
1. add field likeId when return public info
2. fix wukongAddPublicFromLikeRequest
> feat:add field likeId when return public info

- app/bigmodel.go
- app/bigmodel_dto.go
- controller/bigmodel.go
- controller/bigmodel_request.go
- domain/bigmodel.go
- domain/dp_bigmodel.go
- domain/repository/wukong.go
- infrastructure/mongodb/doc.go
- infrastructure/mongodb/wukong_picture.go
- infrastructure/repositories/wukong_picture.go
1. add new field "level" into pictureItem
2. new interface: get official publics picture
3. fix add public, fix request: wukongAddPublicFromLikeRequest
> new interface: get official publics

- app/bigmodel.go
> fix:field toltal of  pagintor

- controller/course.go
- course/domain/dp.go
- course/infrastructure/repositoryimpl/player.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
update list
Update dp.go
update list
remove print, update swag docs
> fix:course list

- infrastructure/authingimpl/user.go
> clean code

- app/bigmodel.go
- app/bigmodel_dto.go
- controller/bigmodel.go
- domain/dp_bigmodel.go
> fix:validate wukong cmd

- controller/course.go
- course/app/course.go
- course/app/dto.go
- course/domain/user.go
- course/infrastructure/repositoryimpl/dataobject.go
- server/gin.go
add course get submissions + clean code
> add course get submissions

- controller/course.go
- course/app/course.go
- course/app/dto.go
- course/domain/repository/course.go
- course/domain/repository/player.go
- course/infrastructure/repositoryimpl/course.go
- course/infrastructure/repositoryimpl/doc.go
- course/infrastructure/repositoryimpl/mongodb.go
- course/infrastructure/repositoryimpl/player.go
- course/infrastructure/repositoryimpl/work.go
- server/gin.go
1. 增加接口：个人中心查询我的课程
2. 增加接口：获取作业详情
3. 增加接口：获取已报名用户信息
> add course user list, get assignment, get reginfo

- cloud/app/dto.go
- cloud/app/internal.go
- cloud/app/pod.go
- cloud/domain/pod.go
- cloud/domain/repository/error.go
- cloud/domain/repository/pod.go
- cloud/infrastructure/repositoryimpl/pgsql.go
- cloud/infrastructure/repositoryimpl/pod.go
- common/infrastructure/pgsql/dao.go
- controller/cloud.go
1. add field id into cloudconf
2. fix get pod info returns
3. set running or failed while watch call
> fix: get cloudconf

- cloud/app/cloud.go
- cloud/app/dto.go
- cloud/app/error.go
- cloud/app/pod.go
- cloud/domain/cloud.go
- cloud/domain/dp.go
- cloud/domain/pod.go
- cloud/domain/service/service.go
- controller/cloud.go
1. fix running pod caculate error
2. change func name
3. opt can subscribe judge
> fix: fix pod

- cloud/app/cloud.go
- cloud/app/dto.go
- cloud/domain/pod.go
- cloud/domain/service/service.go
- controller/cloud.go
1. add hasholding while return cloudconf
2. fix running pod caculate error
3. change func name
4. opt can subscribe judge
5. visitor can get cloud conf
> feat: cloud conf, hasholding and visitor get cloud conf

- cloud/app/message.go
- cloud/infrastructure/repositoryimpl/pod.go
> adjust format

- course/infrastructure/repositoryimpl/record.go
> fix add course record

- competition/infrastructure/repositoryimpl/work.go
> fix competition submit date

- async-server/app/async.go
- async-server/domain/dp.go
- async-server/domain/pool/pool.go
- async-server/domain/repository/wukongreuqest.go
- async-server/domain/request.go
- async-server/infrastructure/bigmodelimpl/bigmodelimpl.go
- async-server/infrastructure/repositoryimpl/dataobject.go
- async-server/infrastructure/repositoryimpl/pgsql.go
- async-server/infrastructure/repositoryimpl/table.go
- async-server/infrastructure/repositoryimpl/wukongrequest.go
- async-server/infrastructure/watchimpl/impl.go
- async-server/main.go
- bigmodel/app/async.go
- bigmodel/domain/message/message.go
- common/infrastructure/pgsql/dao.go
- infrastructure/messages/async.go
- infrastructure/messages/config.go
fix: add field status for TWuKongTask
fix repository interface and impl
fix watcher
> wukong async task & message

- app/inference.go
- controller/inference.go
- domain/inference.go
- infrastructure/inferenceimpl/impl.go
- infrastructure/messages/message.go
- infrastructure/messages/sender.go
- infrastructure/messages/subscribe.go
> fix: get resource level

- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
show avatar of owner in user's likes
> feat: list likes with owner avatar

- controller/bigmodel.go
we rebuild api wukongRank, make it to a wss api
> feat: modify api WuKongRank to wss

- bigmodel/infrastructure/repositoryimpl/wukongtask.go
- controller/bigmodel.go
fix: get user rank
fix: return rank once in api wukongrank
minor updates
> fix: wukong rank

- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/domain/dp.go
- bigmodel/infrastructure/bigmodels/config.go
- bigmodel/infrastructure/bigmodels/service.go
- bigmodel/infrastructure/bigmodels/wukong.go
- controller/bigmodel_request.go
1. support 2 and 4 picture of wukong generate
> feat: support multiple picture inference of wukong

- async-server/app/async.go
- async-server/app/message.go
- async-server/domain/bigmodel/bigmodel.go
- async-server/domain/pool/pool.go
- async-server/domain/repository/asynctask.go
- async-server/domain/request.go
- async-server/infrastructure/bigmodelimpl/bigmodelimpl.go
- async-server/infrastructure/repositoryimpl/asynctask.go
- async-server/infrastructure/watchimpl/impl.go
- async-server/main.go
1. adapt async task for wukong_4img
> feat: new task for wukong4img

- bigmodel/app/async.go
- bigmodel/app/bigmodel.go
- bigmodel/domain/message/message.go
- common/domain/message/message.go
- infrastructure/messages/async.go
- infrastructure/messages/bigmodel.go
- infrastructure/messages/config.go
- infrastructure/messages/subscribe.go
1. refactor message format of bigmodel
2. add new message handle to solve differenet message situation
> refactor msg sender of bigmodel

- bigmodel/app/async.go
- bigmodel/domain/message/message.go
- infrastructure/messages/bigmodel.go
- infrastructure/messages/message.go
- infrastructure/messages/subscribe.go
- message-server/handler.go
1. implement message handle inferface that #335  mentioned
> feat: implement bigmodel handler

- async-server/infrastructure/repositoryimpl/asynctask.go
- async-server/infrastructure/repositoryimpl/dataobject.go
- async-server/infrastructure/repositoryimpl/table.go
- bigmodel/app/async.go
- infrastructure/messages/subscribe.go
- message-server/config.go
create type JSONMap and implement Scan & Value function to support read & write json data in pgsql
> fix: async handle waiting task

- async-server/app/task.go
- async-server/domain/repository/asynctask.go
- async-server/infrastructure/repositoryimpl/asynctask.go
- async-server/infrastructure/repositoryimpl/dataobject.go
- async-server/main.go
- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/domain/async/async.go
- bigmodel/infrastructure/asynccli/async.go
- config/config.go
- controller/bigmodel.go
- controller/bigmodel_request.go
- infrastructure/messages/subscribe.go
- message-server/main.go
- server/gin.go
task information not depends db in module bigmodel but depends db in module async-server client.
it reduce coupling between bigmodel and pgsql
> refactor: add new interface to get task info

- async-server/domain/dp.go
- async-server/domain/request.go
- async-server/infrastructure/bigmodelimpl/bigmodelimpl.go
- async-server/infrastructure/repositoryimpl/dataobject.go
- bigmodel/app/async.go
- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- controller/bigmodel_request.go
- message-server/handler.go
> fix: async-server/domain add new vo taskType

- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/domain/service/service.go
since we need judge like and public wukong picture we inferenced, so it is necessary to return islike & ispublic while call getlastwukongtask
> return islike&ispublic while getlastwukongtask

- bigmodel/app/bigmodel.go
- bigmodel/domain/bigmodel.go
- bigmodel/domain/dp.go
- bigmodel/domain/service/service.go
- bigmodel/infrastructure/repositoryimpl/wukong_picture.go
add value object to field obspath
> fix: change field obspath type

- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/app/taichu.go
- bigmodel/domain/bigmodel/models.go
- bigmodel/infrastructure/bigmodels/config.go
- bigmodel/infrastructure/bigmodels/vqa.go
- controller/bigmodel.go
- controller/bigmodel_request.go
> feat: vqa_hf

- user/app/dto.go
- user/app/follower.go
- user/app/following.go
- user/app/register.go
- user/app/updatebaseinfo.go
- user/app/user.go
- user/domain/dp.go
- user/domain/repository/user.go
- user/domain/user.go
- user/infrastructure/repositoryimpl/dataobject.go
- user/infrastructure/repositoryimpl/doc.go
- user/infrastructure/repositoryimpl/mongodb.go
- user/infrastructure/repositoryimpl/user.go
> refactor: user, for user module

- controller/activity.go
- controller/course.go
- controller/dataset.go
- controller/following.go
- controller/like.go
- controller/login.go
- controller/model.go
- controller/project.go
- controller/search.go
- controller/user.go
- controller/user_request.go
refactor: common controller, part 3
> refactor: user, common controller

- controller/user.go
- controller/user_request.go
- server/gin.go
- user/app/email.go
- user/app/user.go
- user/domain/login/login.go
- user/infrastructure/logincli/logincli.go
> feat: new interfaces of email

- app/login.go
- controller/user.go
- controller/user_request.go
- domain/authing/user.go
- infrastructure/authingimpl/email.go
- infrastructure/authingimpl/user.go
- user/app/dto.go
- user/app/email.go
- user/app/error.go
implement of email bind & send code interface
> feat: implement interfaces of email

- controller/competition.go
- controller/course.go
- controller/dataset.go
- controller/evaluate.go
- controller/inference.go
- controller/middleware.go
- controller/model.go
- controller/project.go
- controller/repofile.go
- controller/training.go
- controller/user.go
feat: add email check middleware for api
fix: set new token while bind email
feat: add mail check middleware for some api
> feat: add middleware for api

- async-server/app/task.go
- async-server/domain/repository/asynctask.go
- async-server/infrastructure/repositoryimpl/asynctask.go
- bigmodel/app/bigmodel.go
- bigmodel/domain/async/async.go
- bigmodel/infrastructure/asynccli/async.go
- controller/bigmodel.go
wukong ranking and wukong task interface don't required task_type anymore
> fix: wukong task

- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/app/luojia.go
- bigmodel/domain/bigmodel/models.go
- bigmodel/infrastructure/bigmodels/config.go
- bigmodel/infrastructure/bigmodels/luojia.go
- bigmodel/infrastructure/bigmodels/vqa.go
- controller/bigmodel.go
- controller/bigmodel_request.go
> feat: luojia hf

- user/domain/dp.go
> fix: user max desc

- controller/login.go
- domain/authing/user.go
- infrastructure/authingimpl/user.go
no longer receive user email while login
> fix: do not receive user email while login

- bigmodel/app/aidetector.go
- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/app/error.go
- bigmodel/domain/bigmodel.go
- bigmodel/domain/bigmodel/models.go
- bigmodel/domain/dp.go
- bigmodel/infrastructure/bigmodels/aidetector.go
- bigmodel/infrastructure/bigmodels/config.go
- bigmodel/infrastructure/bigmodels/error.go
- bigmodel/infrastructure/bigmodels/service.go
- controller/bigmodel.go
- controller/bigmodel_request.go
1. feat: ai detector
2. fix: zh max length
> feat: ai detector

- app/login.go
- controller/login.go
- domain/login.go
- infrastructure/authingimpl/email.go
- infrastructure/mongodb/doc.go
- infrastructure/mongodb/login.go
- infrastructure/repositories/login.go
- user/app/email.go
- user/app/error.go
1. save email while user login
2. check email if email bind error is duplicate bind
> fix: check email and bind it while code is userduplicateBind

- controller/access.go
- controller/base.go
- controller/bigmodel.go
- controller/cloud.go
- controller/config.go
- controller/evaluate.go
- controller/finetune.go
- controller/inference.go
- controller/login.go
- controller/middleware.go
- controller/training.go
- controller/user.go
- utils/util.go
fix: cookie token
feat: csrf-token
> feat: double token verify

- bigmodel/app/aidetector.go
- bigmodel/app/dto.go
- bigmodel/domain/dp.go
- controller/bigmodel.go
- controller/bigmodel_request.go
record bigmodel ai detector access log
> feat: send aidetector operation log

- async-server/infrastructure/watchimpl/impl.go
- async-server/main.go
- bigmodel/domain/service/service.go
- bigmodel/infrastructure/bigmodels/desc_picture.go
- bigmodel/infrastructure/bigmodels/luojia.go
- bigmodel/infrastructure/bigmodels/service.go
- bigmodel/infrastructure/bigmodels/vqa.go
- bigmodel/infrastructure/repositoryimpl/mongodb.go
- cloud/domain/service/service.go
- common/infrastructure/mongo/utils.go
- competition/infrastructure/repositoryimpl/mongodb.go
- course/app/course.go
- course/infrastructure/repositoryimpl/mongodb.go
- infrastructure/bigmodels/config.go
- infrastructure/bigmodels/desc_picture.go
- infrastructure/bigmodels/service.go
- infrastructure/mongodb/utils.go
- infrastructure/repositories/competition_do.go
- infrastructure/repositories/login.go
- infrastructure/repositories/resource.go
- internal-server/main.go
- main.go
- message-server/handler.go
- message-server/main.go
- user/infrastructure/repositoryimpl/mongodb.go
> fix: ensure proper handling of function's error return values

- controller/login.go
- user/app/dto.go
- user/app/email.go
- user/app/user.go
create account in gitlab while user login reuturns email info
to solve email bind problem
> fix: create gitlab account while user login with email

- async-server/infrastructure/repositoryimpl/dataobject.go
- controller/resource.go
> fix: must handle failed type assertions

- user/infrastructure/repositoryimpl/user.go
> fix: find follower

- user/infrastructure/repositoryimpl/user.go
> fix: find follwer2

- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/app/taichu.go
- bigmodel/domain/bigmodel.go
- bigmodel/domain/dp.go
- controller/bigmodel.go
- controller/bigmodel_request.go
validate desc for genpicture of taichu
IT-ICSL  problem 52
> feat: validate desc

- bigmodel/domain/dp.go
> feat: validate question

- app/like.go
- app/resource.go
- domain/dp_resource.go
> fix: not allowed private resource

- app/activity.go
- app/dataset.go
- app/fork.go
- app/model.go
- app/project.go
- controller/activity.go
- domain/activity.go
- infrastructure/mongodb/activity.go
- infrastructure/mongodb/doc.go
- infrastructure/repositories/activity.go
> feat: dont show private activity

- config/config.go
- domain/config.go
- domain/dp_user.go
> fix: use default avatar if avatar id invalid

- controller/access.go
- go.mod
- go.sum
jwt-go -> golang-jwt/jwt/v4 v4.5.0
> fix: replace jwt-go component

- bigmodel/infrastructure/bigmodels/luojia.go
- bigmodel/infrastructure/bigmodels/vqa.go
> 【fix】update uploadfile_path invaild bug

- app/activity.go
- app/dataset.go
- app/fork.go
- app/model.go
- app/project.go
- domain/dataset.go
- domain/model.go
- domain/project.go
> fix: activity delete project error

- controller/bigmodel.go
- controller/cloud.go
- controller/dataset.go
- controller/evaluate.go
- controller/inference.go
- controller/login.go
- controller/model.go
- controller/project.go
- controller/training.go
- utils/log.go
1. user: login, logout, logup
2. project, model, dataset: create, delete
3. jupyter: create
4. gradio: create
5. aim: create, delete
6. training: create, delete
7. wukong: create task, delete like picture, delete public picture
> feat: add log for import operator of resource

- app/like.go
> fix: like repo error

- common/infrastructure/redis/dao.go
- common/infrastructure/redis/db.go
- controller/base.go
- controller/login.go
- controller/user.go
- go.mod
- go.sum
- infrastructure/redis/redis.go
- infrastructure/repositories/access.go
- main.go
- server/gin.go
> feat: private token in cookie, no session

- domain/authing/user.go
- domain/dp_user.go
- infrastructure/authingimpl/user.go
fix bug of IT-ICSL issue 26: cannot filter error avatarid
> fix: avatarid filter

- controller/base.go
> fix: fix visitor cannot access proj

- common/infrastructure/redis/dao.go
> fix: get expiry time from config

- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/domain/dp.go
- controller/bigmodel.go
- controller/bigmodel_request.go
- utils/validator.go
new feature for IT-ICSL, this is the xss and validate modify only in part of bigmodel
> feat: xss and format validate of user input, part of bigmodel

- bigmodel/infrastructure/repositoryimpl/wukong_picture.go
- utils/validator.go
> fix: regexp function error

- infrastructure/authingimpl/email.go
handle bindemail service returns in IT-ICSL system
> fix: add new respone situation

- controller/base.go
- controller/resource.go
- controller/response.go
> fix: code check for clouddragon

- controller/base.go
fix the way get csrftoken #451
> fix: get csrftoken from header

- server/gin.go
> fix: fix bug of #474 take

- controller/bigmodel.go
- utils/validator.go
validate picture extented name, only .jpg/.jepg/.png allowed
> feat: validate describepicture & luojianet picture upload format

- controller/bigmodel.go
> feat: validate picture name for vqa

- utils/util.go
> fix: math/rand -> crypto/rand

- bigmodel/app/dto.go
check wukong inference style length
> fix: check wukong input style length

- bigmodel/app/dto.go
- bigmodel/domain/dp.go
- competition/domain/dp.go
- course/domain/dp.go
- domain/dp_training.go
must use xss convert first in input validate function, it might over length if we do xss convert after check input length
> fix: xss convert first in input validate

- course/app/dto.go
- course/domain/dp.go
enhance limit of courseid, lessionid, pointid limit to 50
> fix: course play input validate fix

- user/app/follower.go
user's follower total count error
> fix: fix follower total count

- controller/cloud.go
- controller/inference.go
1. only MindSpore account gradio resource can be accessed
2. remove api of subscribe jupyter
> feat: only MindSpore account gradio rsource can be accessed

- controller/inference.go
> fix: resource not allowed error code return

- controller/base.go
fix token not expire while logout
> fix: expire encode username while logout

- controller/finetune_request.go
- domain/finetune.go
- utils/validator.go
> fix: input of finetune create

- controller/cloud.go
recovery interface of jupyter which deleted in ICSL
> fix: recovery interface of jupyter

- controller/inference.go
> fix: allow all account create inference

- bigmodel/app/bigmodel.go
- bigmodel/app/dto.go
- bigmodel/domain/api_info.go
- bigmodel/domain/api_service.go
- bigmodel/domain/dp.go
- bigmodel/domain/repository/api_info.go
- bigmodel/domain/repository/api_service.go
- bigmodel/infrastructure/bigmodels/config.go
- bigmodel/infrastructure/bigmodels/wukong.go
- bigmodel/infrastructure/repositoryimpl/api_info.go
- bigmodel/infrastructure/repositoryimpl/api_service.go
- bigmodel/infrastructure/repositoryimpl/dataobject.go
- bigmodel/infrastructure/repositoryimpl/doc.go
- bigmodel/infrastructure/repositoryimpl/mongodb.go
- config/config.go
- controller/base.go
- controller/bigmodel.go
- controller/bigmodel_request.go
- controller/user.go
- server/gin.go
- user/app/dto.go
- user/domain/dp.go
1. apply for api
2. call api record
3. user get regsterinfo
4. get user api info
> feat: bigmodel api service

- bigmodel/infrastructure/bigmodels/baichuan.go
- controller/bigmodel.go
1. change interface url of baichuan
2. change baichuan bigmodel inputs struct
> fix: interface and field of baichuan bigmodel inputs

- bigmodel/app/dto.go
- controller/bigmodel.go
repetition_penalty：1.05
top_k = 0
top_p = 1.0
temperature = 1.0
> fix: modify default set of baichuanCmd

- async-server/config/config.go
- async-server/main.go
- bigmodel/app/aidetector.go
- bigmodel/app/async.go
- bigmodel/app/baichuan.go
- bigmodel/app/bigmodel.go
- bigmodel/app/codegeex.go
- bigmodel/app/luojia.go
- bigmodel/app/pangu.go
- bigmodel/app/taichu.go
- bigmodel/config/config.go
- bigmodel/domain/event.go
- bigmodel/domain/message/message.go
- bigmodel/infrastructure/messageadapter/impl.go
- bigmodel/messagequeue/bigmodel.go
- config/config.go
- infrastructure/messages/message.go
- infrastructure/messages/sender.go
- infrastructure/messages/subscribe.go
- main.go
- message-server/config.go
- message-server/handler.go
- message-server/main.go
- server/gin.go
config changes:
1. async-server: bigmodel
2. xihe-server: bigmodel
3. message-server: MQTopics
> update message of bigmodel

- app/training.go
- config/config.go
- config/training.go
- controller/messagequeue/training.go
- controller/training.go
- domain/event.go
- domain/message/message.go
- domain/message/training.go
- infrastructure/messages/subscribe.go
- infrastructure/messages/training.go
- infrastructure/messages/traning.go
- internal-server/main.go
- message-server/config.go
- message-server/handler.go
- message-server/main.go
- messagequeue/training.go
- server/gin.go
config pr: https://github.com/opensourceways/infra-mindspore/pull/1235
> update message of training

- common/domain/dp.go
- controller/base.go
- controller/user_points.go
- points/app/dto.go
- points/app/message.go
- points/app/user_points.go
- points/domain/user_points.go
- points/infrastructure/repositoryadapter/task.go
- points/infrastructure/repositoryadapter/task_do.go
- points/infrastructure/repositoryadapter/user_points.go
- points/infrastructure/repositoryadapter/user_points_do.go
- points/infrastructure/ruleimpl/tasks.yaml
- points/messagequeue/user_points.go
support multi languages for task name and description。
> support multi languages for task name and description

- bigmodel/infrastructure/messageadapter/impl.go
- message-server/config.go
- message-server/main.go
config add：
inference_async_finish
> points of bigmodel wukong async inference finished

- bigmodel/app/aidetector.go
- bigmodel/app/baichuan.go
- bigmodel/app/codegeex.go
- bigmodel/app/luojia.go
- bigmodel/app/pangu.go
- bigmodel/app/taichu.go
- bigmodel/domain/event.go
- bigmodel/domain/message/message.go
- bigmodel/infrastructure/messageadapter/impl.go
- bigmodel/messagequeue/bigmodel.go
- message-server/config.go
- message-server/main.go
config update:
1. message-server: bigmodel_finished
> feat: points of bigmodel inference finished event

- controller/finetune_request.go
- domain/config.go
- domain/dp_finetune.go
- domain/finetune.go
- infrastructure/finetuneimpl/impl.go
- infrastructure/repositories/finetune_dos.go
to align fronted and backend validation
> make finetuneName value object

- app/finetune_dto.go
- domain/finetune.go
- infrastructure/repositories/finetune_dos.go
> fix: replace trainingName with fintuneName in FintuneSummary

- Dockerfile
按照安全设计规范v2.3修改文件权限：
/opt/app 改成700
/opt/app/points 改成750
本地Docker Build后检查权限：
Jenkins部署后检查权限：
> /opt/app 与 /opt/app/points修改权限

- controller/access.go
- controller/base.go
- controller/middleware.go
- controller/model.go
- controller/project.go
- controller/repofile.go
- infrastructure/authingimpl/user.go
- server/gin.go
- utils/clear.go
1. clean platformToken
2. clean access token
3. clean detoken in checkBigmodelApiToken
> clean sensitive data

- controller/base.go
- controller/login.go
1. clean accesstoken in login
2. fix: pass address of payload
> clean accesstoken in login
